# Generated by Django 5.2.17 on 2026-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0006_order_flow_payment_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="offers", to="cafe.menuitem"
            ),
        ),
    ]
