# Generated by Django 5.2.17 on 2026-09-18 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_payment_gateway_and_order_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafetable',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('WAITING_FOOD', 'Waiting Food'), ('FOOD_READY', 'Food Ready'), ('FINISHED', 'Finished'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('ENGAGEMENT', 'Engagement'), ('ANNIVERSARY', 'Anniversary'), ('GRADUATION', 'Graduation'), ('PRIVATE_GATHERING', 'Private Gathering'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('DEPOSIT_PAID', 'Deposit paid'), ('PAID', 'Fully paid')], default='UNPAID', max_length=20)),
                ('decoration', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cafe.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('tables', models.ManyToManyField(blank=True, related_name='reservations', to='cafe.cafetable')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
